pro_lab/app_lab/urls.py
from app_lab.views import (
    AnaliseCreateView, AnaliseDeleteView, AnaliseDetailView, AnaliseListView, AnaliseUpdateView, ExameCreateView,
    ExameDeleteView, ExameDetailView, ExameListView, ExameUpdateView, gerenciar_analises, IndexView, PacienteCreateView,
    PacienteDeleteView, PacienteDetailView, PacienteListView, PacienteUpdateView, ResultadoCreateView,
    ResultadoDeleteView, ResultadoDetailView, ResultadoListView, ResultadoUpdateView, UsuarioCreateView,
    UsuarioDeleteView, UsuarioDetailView, UsuarioListView, UsuarioUpdateView,
    )
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
        # Página inicial
        path("", IndexView.as_view(), name = "index"),
        path('relatorio/analises/', views.relatorio_analises, name = 'relatorio_analises'),
        path(
                'relatorio/pacientes_atendidos/', views.relatorio_pacientes_atendidos,
                name = 'relatorio_pacientes_atendidos'
                ),
        path('relatorio/analises_diarias/', views.relatorio_analises_diarias, name = 'relatorio_analises_diarias'),
        # Autenticação
        path("login/", auth_views.LoginView.as_view(), name = "login"),
        path("logout/", auth_views.LogoutView.as_view(next_page = "/login/"), name = "logout"),

        # Usuários
        path("usuarios/", UsuarioListView.as_view(), name = "usuario_list"),
        path("usuarios/novo/", UsuarioCreateView.as_view(), name = "usuario_create"),
        path("usuarios/<int:pk>/", UsuarioDetailView.as_view(), name = "usuario_detail"),
        path("usuarios/<int:pk>/editar/", UsuarioUpdateView.as_view(), name = "usuario_update"),
        path("usuarios/<int:pk>/deletar/", UsuarioDeleteView.as_view(), name = "usuario_delete"),

        # Pacientes
        path('paciente/<int:paciente_id>/', views.detalhes_paciente, name = 'detalhes_paciente'),
        path('paciente/<int:paciente_id>/analises/', views.adicionar_analises, name = 'adicionar_analises'),

        path("pacientes/", PacienteListView.as_view(), name = "paciente_list"),
        path("pacientes/novo/", PacienteCreateView.as_view(), name = "paciente_create"),
        path("pacientes/<int:pk>/", PacienteDetailView.as_view(), name = "paciente_detail"),
        path("pacientes/<int:pk>/editar/", PacienteUpdateView.as_view(), name = "paciente_update"),
        path("pacientes/<int:pk>/deletar/", PacienteDeleteView.as_view(), name = "paciente_delete"),
        path("pacientes/<int:paciente_id>/analises/", gerenciar_analises, name = "gerenciar_analises"),

        # Análises
        path("analises/", AnaliseListView.as_view(), name = "analise_list"),
        path("analises/novo/", AnaliseCreateView.as_view(), name = "analise_create"),
        path("analises/<int:pk>/", AnaliseDetailView.as_view(), name = "analise_detail"),
        path("analises/<int:pk>/editar/", AnaliseUpdateView.as_view(), name = "analise_update"),
        path("analises/<int:pk>/deletar/", AnaliseDeleteView.as_view(), name = "analise_delete"),

        # Resultados
        path("resultados/", ResultadoListView.as_view(), name = "resultado_list"),
        path("resultados/novo/", ResultadoCreateView.as_view(), name = "resultado_create"),
        path("resultados/<int:pk>/", ResultadoDetailView.as_view(), name = "resultado_detail"),
        path("resultados/<int:pk>/editar/", ResultadoUpdateView.as_view(), name = "resultado_update"),
        path("resultados/<int:pk>/deletar/", ResultadoDeleteView.as_view(), name = "resultado_delete"),

        # Exames
        path("exames/", ExameListView.as_view(), name = "exame_list"),
        path("exames/novo/", ExameCreateView.as_view(), name = "exame_create"),
        path("exames/<int:pk>/", ExameDetailView.as_view(), name = "exame_detail"),
        path("exames/<int:pk>/editar/", ExameUpdateView.as_view(), name = "exame_update"),
        path("exames/<int:pk>/deletar/", ExameDeleteView.as_view(), name = "exame_delete"),
        ]

pro_lab/pro_lab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_lab.urls')),
]

pro_lab/app_lab/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_countries.fields import CountryField


# Usuário personalizado
class Usuario(AbstractUser):
    is_medico = models.BooleanField(default=False)


class Exame(models.Model):
    nome = models.CharField(max_length=255, unique=True)  # Nome do exame
    descricao = models.TextField(blank=True, null=True)  # Detalhes sobre o exame
    valor_referencia = models.CharField(
        max_length=255, help_text="Exemplo: 4.5 - 6.0"
    )  # Valor de referência
    unidade_si = models.CharField(
        max_length=50, help_text="Exemplo: g/dL, mmol/L"
    )  # Unidade no sistema internacional
    prazo_resultado = models.PositiveIntegerField(
        help_text="Prazo para resultado em dias"
    )  # Prazo de entrega do resultado
    ativo = models.BooleanField(default=True)  # Indica se o exame está disponível
    data_criacao = models.DateTimeField(
        auto_now_add=True
    )  # Data de criação do registro
    data_atualizacao = models.DateTimeField(auto_now=True)  # Data da última atualização

    class Meta:
        verbose_name_plural = "Exames"

    def __str__(self):
        return self.nome


# Modelo de Paciente
class Paciente(models.Model):
    nome = models.CharField(max_length=255)
    data_nascimento = models.DateField()
    genero = models.CharField(
        max_length=10,
        choices=[
            ("Masculino", "Masculino"),
            ("Feminino", "Feminino"),
            ("Outro", "Outro"),
        ],
    )
    telefone = models.CharField(max_length=15)
    residencia = models.CharField(max_length=100, blank=True, null=True)
    nacionalidade = CountryField(
        blank=False, null=False, default="MZ"
    )  # Exemplo: Moçambique como padrão
    numero_identificacao = models.CharField(max_length=20, blank=True, null=True)
    exames = models.ManyToManyField(
        "Exame", blank=True
    )  # Relacionamento com o modelo Exame
    data_entrada = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Pacientes"

    def __str__(self):
        return self.nome


# Modelo de Análise
class Analise(models.Model):
    paciente = models.ForeignKey(
        Paciente, on_delete=models.CASCADE, related_name="analises"
    )
    tipo = models.ForeignKey(Exame, on_delete=models.CASCADE)
    descricao = models.TextField(blank=True)
    data_realizacao = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=20,
        choices=[
            ("pendente", "Pendente"),
            ("em andamento", "Em Andamento"),
            ("concluída", "Concluída"),
        ],
        default="pendente",
    )

    class Meta:
        verbose_name_plural = "Análises"

    def __str__(self):
        return f"{self.tipo} - {self.paciente.nome}"


# Modelo de Resultado
class Resultado(models.Model):
    analise = models.ForeignKey(
        Analise, on_delete=models.CASCADE, related_name="resultados"
    )
    dados = models.TextField()
    validado = models.BooleanField(default=False)
    validador = models.ForeignKey(
        Usuario, on_delete=models.SET_NULL, null=True, blank=True
    )
    data_validacao = models.DateTimeField(blank=True, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Resultados"

    def __str__(self):
        return f"Resultado de {self.analise.tipo} para {self.analise.paciente.nome}"


# Modelo de Material e Consumível
class MaterialBase(models.Model):
    nome = models.CharField(max_length=100)
    quantidade = models.PositiveIntegerField()
    estoque_minimo = models.PositiveIntegerField(default=10)
    validade = models.DateField()
    descricao = models.TextField(blank=True, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Materiais e Consumíveis"
        abstract = True

    def __str__(self):
        return f"{self.nome} - Estoque: {self.quantidade} - Validade: {self.validade}"


class Material(MaterialBase):
    pass


class Consumivel(MaterialBase):
    pass


# Modelo de Banco de Sangue
class TipoSanguineo(models.Model):
    tipo = models.CharField(
        max_length=3,
        choices=[
            ("A-", "A-"),
            ("A+", "A+"),
            ("B-", "B-"),
            ("B+", "B+"),
            ("AB-", "AB-"),
            ("AB+", "AB+"),
            ("O-", "O-"),
            ("O+", "O+"),
        ],
    )
    descricao = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Tipos Sanguineos"

    def __str__(self):
        return self.tipo


class BancoDeSangue(models.Model):
    tipo_sanguineo = models.ForeignKey(TipoSanguineo, on_delete=models.CASCADE)
    quantidade_em_unidades = models.PositiveIntegerField()
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Bancos de Sangue"

    def __str__(self):
        return f"{self.tipo_sanguineo.tipo} - {self.quantidade_em_unidades} Unidades"


# Modelo de Auditoria
class Auditoria(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)
    acao = models.CharField(max_length=255)
    objeto_afetado = models.CharField(max_length=255)
    data_acao = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Auditorias"

    def __str__(self):
        return f"{self.usuario} {self.acao} em {self.data_acao}"

pro_lab/app_lab/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.utils.timezone import now

from .models import (
    Analise,
    Auditoria,
    BancoDeSangue,
    Consumivel,
    Exame,
    Material,
    Paciente,
    Resultado,
    TipoSanguineo,
    Usuario,
    )

from django import forms
from .models import Exame

class CriarAnalisesForm(forms.Form):
    exames = forms.ModelMultipleChoiceField(
            queryset = Exame.objects.all(),
            widget = forms.CheckboxSelectMultiple,  # Apresenta os exames como checkboxes
            required = True,
            )
    descricao = forms.CharField(
            widget = forms.Textarea,
            required = False,
            help_text = "Descrição adicional (opcional)."
            )
    status = forms.ChoiceField(
            choices = [
                    ("pendente", "Pendente"),
                    ("em andamento", "Em Andamento"),
                    ("concluída", "Concluída"),
                    ],
            initial = "pendente",
            required = True,
            )

# Formulário para o modelo Exame
class ExameForm(forms.ModelForm):
    class Meta:
        model = Exame
        fields = [
                "nome",
                "descricao",
                "valor_referencia",
                "unidade_si",
                "prazo_resultado",
                "ativo",
                ]

# Formulário para o modelo Usuario
class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
                "username",
                "first_name",
                "last_name",
                "email",
                "is_medico",
                "password",
                ]
        widgets = {
                "password": forms.PasswordInput(),
                }

# Formulário para o modelo Paciente
class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = [
                "nome",
                "data_nascimento",
                "genero",
                "telefone",
                "residencia",
                "nacionalidade",
                "numero_identificacao",
                "exames",
                ]

    def clean_data_nascimento(self):
        data = self.cleaned_data["data_nascimento"]
        if data > now().date():
            raise forms.ValidationError("A data de nascimento não pode ser no futuro.")
        return data

# Formulário para o modelo Analise
class AnaliseForm(forms.ModelForm):
    class Meta:
        model = Analise
        fields = ["paciente", "tipo", "descricao", "status"]
        widgets = {
                "paciente" : forms.Select(attrs = {"class": "form-control"}),
                "tipo"     : forms.Select(attrs = {"class": "form-control"}),
                "descricao": forms.Textarea(attrs = {"class": "form-control"}),
                "status"   : forms.Select(attrs = {"class": "form-control"}),
                }

# Formulário para o modelo Resultado
class ResultadoForm(forms.ModelForm):
    class Meta:
        model = Resultado
        fields = ["analise", "dados", "validado", "validador", "data_validacao"]

# Formulário para o modelo Material
class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ["nome", "quantidade", "estoque_minimo", "validade", "descricao"]

    def clean(self):
        cleaned_data = super().clean()
        quantidade = cleaned_data.get("quantidade")
        estoque_minimo = cleaned_data.get("estoque_minimo")
        if quantidade < estoque_minimo:
            raise forms.ValidationError(
                    "A quantidade não pode ser menor que o estoque mínimo."
                    )
        return cleaned_data

# Formulário para o modelo Consumivel
class ConsumivelForm(forms.ModelForm):
    class Meta:
        model = Consumivel
        fields = ["nome", "quantidade", "estoque_minimo", "validade", "descricao"]

# Formulário para o modelo TipoSanguineo
class TipoSanguineoForm(forms.ModelForm):
    class Meta:
        model = TipoSanguineo
        fields = ["tipo", "descricao"]

# Formulário para o modelo BancoDeSangue
class BancoDeSangueForm(forms.ModelForm):
    class Meta:
        model = BancoDeSangue
        fields = ["tipo_sanguineo", "quantidade_em_unidades"]

# Formulário para o modelo Auditoria (geralmente apenas leitura, mas incluído caso seja necessário)
class AuditoriaForm(forms.ModelForm):
    class Meta:
        model = Auditoria
        fields = ["usuario", "acao", "objeto_afetado"]

AnaliseFormset = inlineformset_factory(
        Paciente,
        Analise,
        form = AnaliseForm,
        extra = 1,  # Quantidade inicial de formulários exibidos
        can_delete = True,  # Permitir exclusão de análises
        )

pro_lab/app_lab/templates/app_lab/base.html
{% load static %}
<html lang = 'pt'>
<head>
    <meta charset = 'UTF-8'>
    <meta name = 'viewport' content = 'width=device-width, initial-scale=1.0'>
    <link rel = 'icon' href = "{% static 'images/favicon.ico' %}" type = 'image/x-icon'>
    <title>{% block title %}Sistema de Gestão - Laboratório{% endblock %}</title>
    <link href = 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600&display=swap' rel = 'stylesheet'>
    <link rel = 'stylesheet' href = "{% static 'css/style.css' %}">
   {% load static %}
    <style>
        /* Estilos Globais */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Source Sans Pro', Arial, sans-serif;
            line-height: 1.4em;
            background-color: #555555;
            color: #333;
            font-size: 16px;
            padding-top: 150px;
        }

        /* Cabeçalho */
        header {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background-color: #1e2a37;
            color: #fff;
            padding: 20px;
            text-align: center;
            z-index: 1000;
        }

        header h1 {
            font-size: 2.5em;
            margin-bottom: 0.2em;
        }

        header h2 {
            font-size: 1.2em;
            font-weight: normal;
            margin-top: 10;
        }

        /* Navegaç&atilde;o */
        nav ul {
            list-style-type: none;
            padding: 0;
            margin-top: 20px;
        }

        nav ul li {
            display: inline-block;
            margin-right: 20px;
        }

        a:hover, button:hover {
            text-decoration: none;
            color: #fff;
            background-color: gray;
            font-weight: bold;
            padding: 10px 20px;
            border-radius: 5px;
            transition-duration: 1s;
            transition: background-color 0.3s, transform 0.3s;
        }

        a, button {
            text-decoration: none;
            color: #fff;
            background-color: gray;
            font-weight: bold;
            padding: 5px 10px;
            border-radius: 5px;
            transition-duration: 1s;
            transition: background-color 0.3s, transform 0.3s;
        }

        nav ul li a:hover {
            background-color: darkgray;
            transform: scale(1.05);
        }

        button:hover {
            background-color: #444;
        }

        /* Conteúdo Principal */
        main {
            padding: 20px;
            max-width: 1200px;
            margin: auto;
            background-color: #999999;
            border-radius: 0px 0px 10px 10px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            min-height: calc(100vh - 160px);
        }

        /* Tabelas */
        table {
            width: 100%;
            border-collapse: separate;
            margin: 20px 0;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 4px;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f1f1f1;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:hover {
            background-color: #f1f1f1;
        }

        /* Rodapé */
        footer {
            background-color: #1e2a37;
            color: #fff;
            text-align: center;
            padding: 1px;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        /* Responsividade */
        @media screen and (max-width: 768px) {
            nav ul li {
                display: block;
                margin-bottom: 10px;
            }

            header h1 {
                font-size: 2em;
            }

            header h2 {
                font-size: 1.5em;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>Sistema de Gest&atilde;o Laboratorial</h1>
        <h2>Laborat&oacute;rio Mocimboa da Praia</h2>

        <!-- Bloco de navegação -->
        <nav>
            <ul>
                <li><a href = "{% url 'index' %}">P&aacute;gina Inicial</a></li>
                {% if user.is_authenticated %}
                    <li>Bem-vindo, {{ user.username.upper }}</li>
                    <li>
                        <form method = 'POST' action = "{% url 'logout' %}" style = 'display: inline;'>
                            {% csrf_token %}
                            <button type = 'submit'>Sair</button>
                        </form>
                    </li>
                {% else %}
                    <li><a href = "{% url 'login' %}">Entrar</a></li>
                {% endif %}
                {% if perms.app_lab.add_analise %}
                    <li><a href = "{% url 'usuario_list' %}">Usuários</a></li>
                    <li><a href = "{% url 'analise_create' %}">Adicionar Análise</a></li>
                {% endif %}
                <li><a href = "{% url 'paciente_list' %}">Pacientes</a></li>
                <li><a href = "{% url 'exame_list' %}">Exames</a></li>
                <li><a href = "{% url 'analise_list' %}">Análises</a></li>
                <li><a href = "{% url 'resultado_list' %}">Resultados</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- Conteúdo dinâmico será renderizado aqui -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; {% now 'Y' %} Sistema de Gest&atilde;o Laboratorial. Desenvolvido pelo laboratorista Abdul Daniel Trato.</p>
    </footer>
</body>
</html>

pro_lab/app_lab/templates/app_lab/elatorio_pacientes_atendidos_mes.html
<h1>Relatório de Pacientes Atendidos Este Mês</h1>
{% for paciente in pacientes %}
    <thead>

    </thead>
{% endfor %}
<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Data de Entrada</th>
            <th>Total de Análises</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.nome }}</td>
                <td>{{ paciente.data_entrada }}</td>
                <td>{{ paciente.analises.count }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '3'>Nenhum paciente atendido este mês.</td></tr>
        {% endfor %}
    </tbody>
</table>

pro_lab/app_lab/templates/app_lab/index.html
{% extends 'app_lab/base.html' %}

{% block title %}Sistema de Gest&atilde;o Laboratorial{% endblock %}

{% block content %}
<p>Este sistema foi desenvolvido para simplificar a gest&atilde;o de pacientes, an&aacute;lises, resultados, materiais, Consumiveis e Futuramente
   outras entidades</p>
<section>
    <h2>&Aacute;eas do Sistema</h2>
    <ul>
        <li><a href = "{% url 'usuario_list' %}">Gest&atilde;o de Usu&aacute;rios</a>
            <a href = "{% url 'paciente_list' %}">Gest&atilde;o de Pacientes</a>
            <a href = "{% url 'exame_list' %}">Gest&atilde;o de Exames</a>
            <a href = "{% url 'analise_list' %}">Gest&atilde;o de An&aacute;lises</a>
            <a href = "{% url 'resultado_list' %}">Gest&atilde;o de Resultados</a>
        </li>
    </ul>
</section>
{% endblock %}

pro_lab/app_lab/templates/app_lab/login.html
<!-- templates/registration/login.html -->

{% extends "base.html" %}

{% block content %}
  <div class = 'login-container'>
    <h2>Login</h2>
    <form method = 'post'>
      {% csrf_token %}
      <div class = 'form-group'>
        {{ form.as_p }}
      </div>
      <button type = 'submit'>Login</button>
    </form>
  </div>
{% endblock %}

pro_lab/app_lab/templates/app_lab/relatorio_analises.html
<h1>Relatório de Análises Realizadas</h1>

<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Exame</th>
            <th>Descrição</th>
            <th>Data de Realização</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for analise in analises %}
            <tr>
                <td>{{ analise.paciente.nome }}</td>
                <td>{{ analise.tipo }}</td>
                <td>{{ analise.descricao|default:"Nenhuma descrição" }}</td>
                <td>{{ analise.data_realizacao }}</td>
                <td>{{ analise.status }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '5'>Nenhuma análise registrada.</td></tr>
        {% endfor %}
    </tbody>
</table>

pro_lab/app_lab/templates/app_lab/relatorio_analises_diarias.html
<h1>Relatório de Análises Realizadas Hoje</h1>

<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Exame</th>
            <th>Descrição</th>
            <th>Data de Realização</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for analise in analises %}
            <tr>
                <td>{{ analise.paciente.nome }}</td>
                <td>{{ analise.tipo }}</td>
                <td>{{ analise.descricao|default:"Nenhuma descrição" }}</td>
                <td>{{ analise.data_realizacao }}</td>
                <td>{{ analise.status }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '5'>Nenhuma análise realizada hoje.</td></tr>
        {% endfor %}
    </tbody>
</table>

pro_lab/app_lab/templates/app_lab/relatorio_analises_mensais.html
<h1>Relatório de Análises Realizadas Este Mês</h1>

<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Exame</th>
            <th>Descrição</th>
            <th>Data de Realização</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for analise in analises %}
            <tr>
                <td>{{ analise.paciente.nome }}</td>
                <td>{{ analise.tipo }}</td>
                <td>{{ analise.descricao|default:"Nenhuma descrição" }}</td>
                <td>{{ analise.data_realizacao }}</td>
                <td>{{ analise.status }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '5'>Nenhuma análise realizada este mês.</td></tr>
        {% endfor %}
    </tbody>
</table>

pro_lab/app_lab/templates/app_lab/relatorio_analises_semanais.html
<h1>Relatório de Análises Realizadas Esta Semana</h1>

<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Exame</th>
            <th>Descrição</th>
            <th>Data de Realização</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for analise in analises %}
            <tr>
                <td>{{ analise.paciente.nome }}</td>
                <td>{{ analise.tipo }}</td>
                <td>{{ analise.descricao|default:"Nenhuma descrição" }}</td>
                <td>{{ analise.data_realizacao }}</td>
                <td>{{ analise.status }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '5'>Nenhuma análise realizada esta semana.</td></tr>
        {% endfor %}
    </tbody>
</table>

pro_lab/app_lab/templates/app_lab/relatorio_pacientes_atendidos.html
<h1>Relatório de Pacientes Atendidos</h1>

<table>
    <thead>
        <tr>
            <th>Paciente</th>
            <th>Data de Entrada</th>
            <th>Total de Análises</th>
        </tr>
    </thead>
    <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.nome }}</td>
                <td>{{ paciente.data_entrada }}</td>
                <td>{{ paciente.analises.count }}</td>
            </tr>
        {% empty %}
            <tr><td colspan = '3'>Nenhum paciente atendido.</td></tr>
        {% endfor %}
    </tbody>
</table>